export default {
  login: "caarlos0",
  id: 245435,
  node_id: "MDQ6VXNlcjI0NTQzNQ==",
  avatar_url: "https://avatars.githubusercontent.com/u/245435?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/caarlos0",
  html_url: "https://github.com/caarlos0",
  followers_url: "https://api.github.com/users/caarlos0/followers",
  following_url: "https://api.github.com/users/caarlos0/following{/other_user}",
  gists_url: "https://api.github.com/users/caarlos0/gists{/gist_id}",
  starred_url: "https://api.github.com/users/caarlos0/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/caarlos0/subscriptions",
  organizations_url: "https://api.github.com/users/caarlos0/orgs",
  repos_url: "https://api.github.com/users/caarlos0/repos",
  events_url: "https://api.github.com/users/caarlos0/events{/privacy}",
  received_events_url: "https://api.github.com/users/caarlos0/received_events",
  type: "User",
  site_admin: false,
  name: "Carlos Alexandro Becker",
  company: "@charmbracelet @goreleaser",
  blog: "https://caarlos0.dev",
  location: "Brazil",
  email: null,
  hireable: true,
  bio: "Maintains @goreleaser; \r\nWorks @charmbracelet;",
  twitter_username: "caarlos0",
  public_repos: 94,
  public_gists: 45,
  followers: 3487,
  following: 156,
  created_at: "2010-04-16T12:16:39Z",
  updated_at: "2024-04-17T14:23:59Z",
};
